# Generated by Django 4.2.7 on 2026-08-02 04:35

import apps.players.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='匿名玩家可为空', max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('name', models.CharField(blank=True, help_text='匿名玩家必填', max_length=100, null=True, verbose_name='玩家姓名')),
                ('preference_tags', models.JSONField(blank=True, default=list, help_text='格式: ["推理型", "情感型", "活跃型", "沉浸型", "搞笑型", "领导型", "辅助型", "新手型", "老玩家型"]', validators=[apps.players.models.validate_preference_tags], verbose_name='偏好标签')),
                ('horror_tolerance', models.IntegerField(blank=True, default=0, help_text='0=完全不能接受, 1=轻微, 2=中等, 3=非常喜欢', validators=[apps.players.models.validate_horror_tolerance], verbose_name='恐怖耐受度')),
                ('accept_reverse', models.BooleanField(default=False, verbose_name='是否接受反串')),
                ('history_roles', models.JSONField(blank=True, default=list, help_text='格式: [{"script_id": int, "role_id": int, "role_name": str, "satisfaction": int, "date": "YYYY-MM-DD"}]', validators=[apps.players.models.validate_history_roles], verbose_name='历史角色记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '玩家档案',
                'verbose_name_plural': '玩家档案',
                'db_table': 'player_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text='即使匿名也填写', max_length=100, verbose_name='玩家姓名')),
                ('player_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='玩家电话')),
                ('match_score', models.FloatField(default=0.0, help_text='0-100分', verbose_name='系统匹配度')),
                ('is_manual_adjusted', models.BooleanField(default=False, verbose_name='是否DM手动调整')),
                ('satisfaction', models.IntegerField(blank=True, help_text='1-5星', null=True, verbose_name='事后满意度')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('player_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='players.playerprofile', verbose_name='关联玩家档案')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scripts.role', verbose_name='分配角色')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='scheduling.schedule', verbose_name='所属场次')),
            ],
            options={
                'verbose_name': '角色分配',
                'verbose_name_plural': '角色分配',
                'db_table': 'role_assignments',
                'ordering': ['schedule', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['phone'], name='player_prof_phone_dc4bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['created_at'], name='player_prof_created_7e9328_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['schedule'], name='role_assign_schedul_95cef1_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['player_profile'], name='role_assign_player__8fe62d_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['role'], name='role_assign_role_id_6889b7_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['assigned_at'], name='role_assign_assigne_00ad53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('schedule', 'role')},
        ),
    ]
