# Generated by Django 4.2.7 on 2026-08-02 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='入职日期')),
                ('specialty_types', models.JSONField(default=list, help_text='格式: ["推理", "情感", "机制"]', verbose_name='擅长类型')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='总带本场次')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('consecutive_days', models.IntegerField(default=0, verbose_name='连续工作天数')),
                ('fatigue_warning', models.BooleanField(default=False, verbose_name='疲劳预警')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dm_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'DM主持人档案',
                'verbose_name_plural': 'DM主持人档案',
                'db_table': 'dm_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DMAvailability',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期几')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='是否循环')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='指定日期(非循环时设置)')),
                ('is_unavailable', models.BooleanField(default=False, verbose_name='标记临时不可用')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='dms.dmprofile', verbose_name='DM主持人')),
            ],
            options={
                'verbose_name': 'DM可用时间',
                'verbose_name_plural': 'DM可用时间',
                'db_table': 'dm_availability',
                'ordering': ['dm', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DMTemporaryUnavailable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='请假原因')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已批准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_unavailables', to='dms.dmprofile', verbose_name='DM主持人')),
            ],
            options={
                'verbose_name': 'DM临时不可用/请假',
                'verbose_name_plural': 'DM临时不可用/请假',
                'db_table': 'dm_temporary_unavailable',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dm'], name='dm_temporar_dm_id_32f530_idx'), models.Index(fields=['start_date', 'end_date'], name='dm_temporar_start_d_ead622_idx'), models.Index(fields=['is_approved'], name='dm_temporar_is_appr_eb62ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='DMSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proficiency', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='熟练度(1-5星)')),
                ('play_count', models.IntegerField(default=0, verbose_name='带本次数')),
                ('last_played', models.DateField(blank=True, null=True, verbose_name='上次带本日期')),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='dms.dmprofile', verbose_name='DM主持人')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_skills', to='scripts.script', verbose_name='剧本')),
            ],
            options={
                'verbose_name': 'DM技能熟练度',
                'verbose_name_plural': 'DM技能熟练度',
                'db_table': 'dm_skill',
                'ordering': ['dm', '-proficiency', '-play_count'],
                'indexes': [models.Index(fields=['dm'], name='dm_skill_dm_id_33efde_idx'), models.Index(fields=['script'], name='dm_skill_script__b0073d_idx'), models.Index(fields=['proficiency'], name='dm_skill_profici_de5086_idx')],
                'unique_together': {('dm', 'script')},
            },
        ),
        migrations.AddIndex(
            model_name='dmprofile',
            index=models.Index(fields=['user'], name='dm_profile_user_id_903158_idx'),
        ),
        migrations.AddIndex(
            model_name='dmprofile',
            index=models.Index(fields=['join_date'], name='dm_profile_join_da_a9e4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='dmprofile',
            index=models.Index(fields=['fatigue_warning'], name='dm_profile_fatigue_ed38fd_idx'),
        ),
        migrations.AddIndex(
            model_name='dmavailability',
            index=models.Index(fields=['dm'], name='dm_availabi_dm_id_7d2b53_idx'),
        ),
        migrations.AddIndex(
            model_name='dmavailability',
            index=models.Index(fields=['day_of_week'], name='dm_availabi_day_of__beb129_idx'),
        ),
        migrations.AddIndex(
            model_name='dmavailability',
            index=models.Index(fields=['specific_date'], name='dm_availabi_specifi_89de0e_idx'),
        ),
        migrations.AddIndex(
            model_name='dmavailability',
            index=models.Index(fields=['is_unavailable'], name='dm_availabi_is_unav_d67e39_idx'),
        ),
    ]
