# Generated by Django 4.2.7 on 2026-08-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms', '0001_initial'),
        ('scripts', '0001_initial'),
        ('stores', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', '已分配'), ('dm_confirmed', 'DM已确认'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='assigned', max_length=30, verbose_name='排班状态')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('is_locked', models.BooleanField(default=False, help_text='店长手动锁定后不可被算法修改', verbose_name='是否锁定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='bookings.booking', verbose_name='预约订单')),
                ('dm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='dms.dmprofile', verbose_name='DM主持人')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='stores.room', verbose_name='房间')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='scripts.script', verbose_name='剧本')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'db_table': 'schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('dm_conflict', 'DM时间冲突'), ('room_conflict', '房间时间冲突'), ('time_overlap', '时间重叠')], db_index=True, max_length=30, verbose_name='冲突类型')),
                ('description', models.CharField(max_length=500, verbose_name='冲突描述')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('schedule1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='scheduling.schedule', verbose_name='排班1')),
                ('schedule2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='scheduling.schedule', verbose_name='排班2')),
            ],
            options={
                'verbose_name': '排班冲突',
                'verbose_name_plural': '排班冲突',
                'db_table': 'schedule_conflicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status', 'created_at'], name='schedules_status_ffad71_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['dm', 'status'], name='schedules_dm_id_1679d0_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['room', 'status'], name='schedules_room_id_5d49bd_idx'),
        ),
    ]
