# Generated by Django 4.2.7 on 2026-08-02 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='用户名（冗余）')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('LOCK', '锁定'), ('UNLOCK', '解锁'), ('APPROVE', '审批通过'), ('REJECT', '审批拒绝'), ('EXPORT', '导出'), ('IMPORT', '导入'), ('STATUS_CHANGE', '状态变更')], db_index=True, max_length=30, verbose_name='操作类型')),
                ('target_type', models.CharField(choices=[('USER', '用户'), ('STORE', '门店'), ('ROOM', '房间'), ('SCRIPT', '剧本'), ('ROLE', '角色'), ('DM_PROFILE', 'DM资料'), ('DM_SKILL', 'DM技能'), ('DM_AVAILABILITY', 'DM可用时间'), ('DM_LEAVE', 'DM请假'), ('BOOKING', '预约'), ('SCHEDULE', '排期'), ('AUDIT_LOG', '审计日志'), ('REVIEW', '评价'), ('PLAYER_PROFILE', '玩家资料'), ('ROLE_ASSIGNMENT', '角色分配'), ('OTHER', '其他')], db_index=True, max_length=30, verbose_name='目标类型')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('target_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标名称（冗余）')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='操作详情')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='操作IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='浏览器UA')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败'), ('PENDING', '待处理')], db_index=True, default='SUCCESS', max_length=20, verbose_name='操作状态')),
                ('failure_reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('store', models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='stores.store', verbose_name='所属门店')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_log_target__0238a6_idx'), models.Index(fields=['user', 'created_at'], name='audit_log_user_id_3b54b4_idx'), models.Index(fields=['store', 'created_at'], name='audit_log_store_i_d6ae8e_idx')],
            },
        ),
    ]
