# Generated by Django 4.2.7 on 2026-08-02 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('duration_minutes', models.IntegerField(default=240, verbose_name='时长(分钟)')),
                ('player_count', models.IntegerField(verbose_name='玩家人数')),
                ('preferences', models.JSONField(default=dict, help_text='格式: {"preferred_types": [], "difficulty_preference": int, "is_newbie": bool, "player_notes": str}', verbose_name='偏好设置')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('no_show', '爽约')], default='pending', max_length=20, verbose_name='预约状态')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='客户电话')),
                ('deposit_amount', models.FloatField(default=0, verbose_name='订金金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stores.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'bookings',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='玩家姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, null=True, verbose_name='性别')),
                ('tags', models.JSONField(blank=True, default=list, help_text='格式: ["标签1", "标签2"]', null=True, verbose_name='标签')),
                ('horror_tolerance', models.IntegerField(blank=True, help_text='0-3: 0=完全不能, 1=轻微, 2=中等, 3=很高', null=True, verbose_name='恐怖耐受度')),
                ('accept_reverse', models.BooleanField(default=False, verbose_name='接受反串')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='bookings.booking', verbose_name='所属预约')),
            ],
            options={
                'verbose_name': '预约玩家',
                'verbose_name_plural': '预约玩家',
                'db_table': 'booking_players',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['store', 'date', 'status'], name='bookings_store_i_931942_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_by'], name='bookings_created_29aecb_idx'),
        ),
    ]
