# Generated by Django 4.2.7 on 2026-08-02 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='剧本名称')),
                ('type', models.CharField(choices=[('reasoning', '推理'), ('emotion', '情感'), ('mechanism', '机制'), ('horror', '恐怖'), ('faction', '阵营')], max_length=20, verbose_name='剧本类型')),
                ('player_count', models.JSONField(default=dict, help_text='格式: {"male": 3, "female": 3, "total": 6}', verbose_name='玩家人数')),
                ('duration_minutes', models.IntegerField(verbose_name='时长(分钟)')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难'), (4, '极难')], verbose_name='难度等级')),
                ('status', models.CharField(choices=[('available', '可使用'), ('maintenance', '维护中'), ('offline', '已下线')], default='available', max_length=20, verbose_name='状态')),
                ('age_tip', models.CharField(blank=True, max_length=100, null=True, verbose_name='年龄提示')),
                ('inventory', models.IntegerField(default=1, verbose_name='库存数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='剧本描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='stores.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '剧本',
                'verbose_name_plural': '剧本',
                'db_table': 'script',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('suggested_gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('any', '不限')], default='any', max_length=10, verbose_name='建议性别')),
                ('personality_tags', models.JSONField(default=list, help_text='格式: ["冷静理智", "情感丰富"]', verbose_name='性格标签')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='scripts.script', verbose_name='所属剧本')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'role',
                'ordering': ['id'],
            },
        ),
    ]
