# Generated by Django 4.2.7 on 2026-08-02 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_dm_rating', models.FloatField(default=0.0, verbose_name='平均DM评分')),
                ('avg_script_rating', models.FloatField(default=0.0, verbose_name='平均剧本评分')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='总场次')),
                ('completed_sessions', models.IntegerField(default=0, verbose_name='完成场次')),
                ('completion_rate', models.FloatField(default=0.0, help_text='完场率 = 完成场次 / 总场次', verbose_name='完场率')),
                ('complaint_count', models.IntegerField(default=0, verbose_name='投诉次数')),
                ('turnover_rate', models.FloatField(default=0.0, verbose_name='月均开本次数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='scripts.script', verbose_name='关联剧本')),
            ],
            options={
                'verbose_name': '剧本统计',
                'verbose_name_plural': '剧本统计',
                'db_table': 'script_stats',
                'ordering': ['-turnover_rate', '-avg_script_rating'],
                'indexes': [models.Index(fields=['script'], name='script_stat_script__42349a_idx'), models.Index(fields=['turnover_rate'], name='script_stat_turnove_bde301_idx'), models.Index(fields=['avg_script_rating'], name='script_stat_avg_scr_343d55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_rating', models.IntegerField(blank=True, help_text='玩家对DM主持人的评分', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='DM评分(1-5星)')),
                ('script_rating', models.IntegerField(blank=True, help_text='玩家对剧本的评分', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='剧本评分(1-5星)')),
                ('dm_tags', models.JSONField(blank=True, default=list, help_text='可多选，如: ["沉浸感强","节奏把控好","扶车时机好","准备充分","气氛调节棒"]', verbose_name='DM评价标签')),
                ('script_tags', models.JSONField(blank=True, default=list, help_text='可多选，如: ["剧情精彩","逻辑严密","情感共鸣","机制新颖","角色平衡"]', verbose_name='剧本评价标签')),
                ('comment', models.TextField(blank=True, help_text='玩家的详细文字评价', null=True, verbose_name='文字评论')),
                ('dm_review', models.JSONField(blank=True, default=dict, help_text='DM填写的复盘信息，格式见文档', verbose_name='DM复盘')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='scheduling.schedule', verbose_name='关联排班')),
            ],
            options={
                'verbose_name': '场次评价',
                'verbose_name_plural': '场次评价',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schedule'], name='reviews_schedul_fc0699_idx'), models.Index(fields=['created_at'], name='reviews_created_53b5d6_idx'), models.Index(fields=['dm_rating'], name='reviews_dm_rati_e4d18d_idx'), models.Index(fields=['script_rating'], name='reviews_script__3c8716_idx')],
            },
        ),
    ]
